MODULE zemaxmodule
DESCRIPTION IDL Extension for ZEMAX
VERSION 1.0
SOURCE IDL
BUILD_DATE FEB 28 2009
FUNCTION    ZEMAX       1   IDL_MAXPARAMS KEYWORDS 
PROCEDURE   ZDDECLOSE   0   0              
